#  Copyright (c) 2012-2025, Bund der Pfadfinderinnen und Pfadfinder. This file is part of
#  hitobito_bdp and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/pfadfinden/hitobito_bdp.


# Settings relevant for the hitobito_bdp wagon
# Overrides settings from the main application
application:
  languages:
    de: Deutsch

  # non UI languages for assigning to person#language
  # additional_languages:
  #   en: Englisch

# The person with this email has root access to everything
# This person should only be used by the operators of the application,
# not the customers.
# Initially, a password reset token may be mailed from the application
# to this address to set a password.
root_email: mitglied@pfadfinden.de
